# -*- encoding: utf-8 -*-

=begin
#Nutanix Volumes APIs

#Configure volumes.

The version of the OpenAPI document: 4.0

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

$:.push File.expand_path("../lib", __FILE__)
require "nutanix_volumes/version"

Gem::Specification.new do |s|
  s.name        = "nutanix_volumes"
  s.version     = NutanixVolumes::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["ManageIQ Developers"]
  s.email       = [""]
  s.homepage    = "https://openapi-generator.tech"
  s.summary     = "Nutanix Volumes API"
  s.description = "Ruby gem for Nutanix Volume Management APIs"
  s.license     = "Apache-2.0"
  s.required_ruby_version = ">= 2.7"
  s.metadata    = {}

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
