=begin
#Nutanix Volumes APIs

#Configure volumes.

The version of the OpenAPI document: 4.0

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for NutanixVolumes::CommonV10ConfigFQDN
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe NutanixVolumes::CommonV10ConfigFQDN do
  let(:instance) { NutanixVolumes::CommonV10ConfigFQDN.new }

  describe 'test an instance of CommonV10ConfigFQDN' do
    it 'should create an instance of CommonV10ConfigFQDN' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(NutanixVolumes::CommonV10ConfigFQDN)
    end
  end

  describe 'test attribute "value"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
