=begin
#Nutanix Volumes APIs

#Configure volumes.

The version of the OpenAPI document: 4.0

Generated by: https://openapi-generator.tech
Generator version: 7.17.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for NutanixVolumes::CommonV10StatsDownSamplingOperator
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe NutanixVolumes::CommonV10StatsDownSamplingOperator do
  #let(:instance) { NutanixVolumes::CommonV10StatsDownSamplingOperator.new }

  describe 'test an instance of CommonV10StatsDownSamplingOperator' do
    it 'should create an instance of CommonV10StatsDownSamplingOperator' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(NutanixVolumes::CommonV10StatsDownSamplingOperator)
    end
  end

end
