=begin
#Nutanix Volumes APIs

#Configure volumes.

The version of the OpenAPI document: 4.0

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for NutanixVolumes::CommonV10ConfigIPAddressOrFQDN
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe NutanixVolumes::CommonV10ConfigIPAddressOrFQDN do
  #let(:instance) { NutanixVolumes::CommonV10ConfigIPAddressOrFQDN.new }

  describe 'test an instance of CommonV10ConfigIPAddressOrFQDN' do
    it 'should create an instance of CommonV10ConfigIPAddressOrFQDN' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(NutanixVolumes::CommonV10ConfigIPAddressOrFQDN)
    end
  end

  describe 'test attribute "ipv4"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "ipv6"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "fqdn"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
