=begin
#Nutanix Volumes APIs

#Configure volumes.

The version of the OpenAPI document: 4.0

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for NutanixVolumes::ListIscsiClients200Response
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe NutanixVolumes::ListIscsiClients200Response do
  #let(:instance) { NutanixVolumes::ListIscsiClients200Response.new }

  describe 'test an instance of ListIscsiClients200Response' do
    it 'should create an instance of ListIscsiClients200Response' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(NutanixVolumes::ListIscsiClients200Response)
    end
  end

  describe 'test attribute "metadata"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "data"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
