=begin
#Nutanix Volumes APIs

#Configure volumes.

The version of the OpenAPI document: 4.0

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for NutanixVolumes::VolumesV40ConfigNvmfClientAttachment
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe NutanixVolumes::VolumesV40ConfigNvmfClientAttachment do
  #let(:instance) { NutanixVolumes::VolumesV40ConfigNvmfClientAttachment.new }

  describe 'test an instance of VolumesV40ConfigNvmfClientAttachment' do
    it 'should create an instance of VolumesV40ConfigNvmfClientAttachment' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(NutanixVolumes::VolumesV40ConfigNvmfClientAttachment)
    end
  end

  describe 'test attribute "tenant_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "ext_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "links"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "cluster_reference"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
