=begin
#Nutanix Volumes APIs

#Configure volumes.

The version of the OpenAPI document: 4.0

Generated by: https://openapi-generator.tech
Generator version: 7.17.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for NutanixVolumes::VolumesV40ConfigAuthenticationType
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe NutanixVolumes::VolumesV40ConfigAuthenticationType do
  #let(:instance) { NutanixVolumes::VolumesV40ConfigAuthenticationType.new }

  describe 'test an instance of VolumesV40ConfigAuthenticationType' do
    it 'should create an instance of VolumesV40ConfigAuthenticationType' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(NutanixVolumes::VolumesV40ConfigAuthenticationType)
    end
  end

end
