=begin
#Nutanix Volumes APIs

#Configure volumes.

The version of the OpenAPI document: 4.0

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for NutanixVolumes::VolumesV40ConfigStorageFeatures
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe NutanixVolumes::VolumesV40ConfigStorageFeatures do
  let(:instance) { NutanixVolumes::VolumesV40ConfigStorageFeatures.new }

  describe 'test an instance of VolumesV40ConfigStorageFeatures' do
    it 'should create an instance of VolumesV40ConfigStorageFeatures' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(NutanixVolumes::VolumesV40ConfigStorageFeatures)
    end
  end

  describe 'test attribute "flash_mode"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
