=begin
#Nutanix Volumes APIs

#Configure volumes.

The version of the OpenAPI document: 4.0

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'date'
require 'time'

module NutanixVolumes
  # Metadata associated with this resource. 
  class CommonV10ConfigMetadata
    # A globally unique identifier that represents the owner of this resource. 
    attr_accessor :owner_reference_id

    # The userName of the owner of this resource. 
    attr_accessor :owner_user_name

    # A globally unique identifier that represents the project this resource belongs to. 
    attr_accessor :project_reference_id

    # The name of the project this resource belongs to. 
    attr_accessor :project_name

    # A list of globally unique identifiers that represent all the categories the resource is associated with. 
    attr_accessor :category_ids

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'owner_reference_id' => :'ownerReferenceId',
        :'owner_user_name' => :'ownerUserName',
        :'project_reference_id' => :'projectReferenceId',
        :'project_name' => :'projectName',
        :'category_ids' => :'categoryIds'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'owner_reference_id' => :'String',
        :'owner_user_name' => :'String',
        :'project_reference_id' => :'String',
        :'project_name' => :'String',
        :'category_ids' => :'Array<String>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `NutanixVolumes::CommonV10ConfigMetadata` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `NutanixVolumes::CommonV10ConfigMetadata`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'owner_reference_id')
        self.owner_reference_id = attributes[:'owner_reference_id']
      end

      if attributes.key?(:'owner_user_name')
        self.owner_user_name = attributes[:'owner_user_name']
      end

      if attributes.key?(:'project_reference_id')
        self.project_reference_id = attributes[:'project_reference_id']
      end

      if attributes.key?(:'project_name')
        self.project_name = attributes[:'project_name']
      end

      if attributes.key?(:'category_ids')
        if (value = attributes[:'category_ids']).is_a?(Array)
          self.category_ids = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      pattern = Regexp.new(/^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$/)
      if !@owner_reference_id.nil? && @owner_reference_id !~ pattern
        invalid_properties.push("invalid value for \"owner_reference_id\", must conform to the pattern #{pattern}.")
      end

      if !@owner_user_name.nil? && @owner_user_name.to_s.length > 128
        invalid_properties.push('invalid value for "owner_user_name", the character length must be smaller than or equal to 128.')
      end

      pattern = Regexp.new(/^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$/)
      if !@project_reference_id.nil? && @project_reference_id !~ pattern
        invalid_properties.push("invalid value for \"project_reference_id\", must conform to the pattern #{pattern}.")
      end

      if !@project_name.nil? && @project_name.to_s.length > 128
        invalid_properties.push('invalid value for "project_name", the character length must be smaller than or equal to 128.')
      end

      if !@category_ids.nil? && @category_ids.length > 256
        invalid_properties.push('invalid value for "category_ids", number of items must be less than or equal to 256.')
      end

      if !@category_ids.nil? && @category_ids.length < 1
        invalid_properties.push('invalid value for "category_ids", number of items must be greater than or equal to 1.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if !@owner_reference_id.nil? && @owner_reference_id !~ Regexp.new(/^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$/)
      return false if !@owner_user_name.nil? && @owner_user_name.to_s.length > 128
      return false if !@project_reference_id.nil? && @project_reference_id !~ Regexp.new(/^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$/)
      return false if !@project_name.nil? && @project_name.to_s.length > 128
      return false if !@category_ids.nil? && @category_ids.length > 256
      return false if !@category_ids.nil? && @category_ids.length < 1
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] owner_reference_id Value to be assigned
    def owner_reference_id=(owner_reference_id)
      if owner_reference_id.nil?
        fail ArgumentError, 'owner_reference_id cannot be nil'
      end

      pattern = Regexp.new(/^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$/)
      if owner_reference_id !~ pattern
        fail ArgumentError, "invalid value for \"owner_reference_id\", must conform to the pattern #{pattern}."
      end

      @owner_reference_id = owner_reference_id
    end

    # Custom attribute writer method with validation
    # @param [Object] owner_user_name Value to be assigned
    def owner_user_name=(owner_user_name)
      if owner_user_name.nil?
        fail ArgumentError, 'owner_user_name cannot be nil'
      end

      if owner_user_name.to_s.length > 128
        fail ArgumentError, 'invalid value for "owner_user_name", the character length must be smaller than or equal to 128.'
      end

      @owner_user_name = owner_user_name
    end

    # Custom attribute writer method with validation
    # @param [Object] project_reference_id Value to be assigned
    def project_reference_id=(project_reference_id)
      if project_reference_id.nil?
        fail ArgumentError, 'project_reference_id cannot be nil'
      end

      pattern = Regexp.new(/^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$/)
      if project_reference_id !~ pattern
        fail ArgumentError, "invalid value for \"project_reference_id\", must conform to the pattern #{pattern}."
      end

      @project_reference_id = project_reference_id
    end

    # Custom attribute writer method with validation
    # @param [Object] project_name Value to be assigned
    def project_name=(project_name)
      if project_name.nil?
        fail ArgumentError, 'project_name cannot be nil'
      end

      if project_name.to_s.length > 128
        fail ArgumentError, 'invalid value for "project_name", the character length must be smaller than or equal to 128.'
      end

      @project_name = project_name
    end

    # Custom attribute writer method with validation
    # @param [Object] category_ids Value to be assigned
    def category_ids=(category_ids)
      if category_ids.nil?
        fail ArgumentError, 'category_ids cannot be nil'
      end

      if category_ids.length > 256
        fail ArgumentError, 'invalid value for "category_ids", number of items must be less than or equal to 256.'
      end

      if category_ids.length < 1
        fail ArgumentError, 'invalid value for "category_ids", number of items must be greater than or equal to 1.'
      end

      @category_ids = category_ids
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          owner_reference_id == o.owner_reference_id &&
          owner_user_name == o.owner_user_name &&
          project_reference_id == o.project_reference_id &&
          project_name == o.project_name &&
          category_ids == o.category_ids
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [owner_reference_id, owner_user_name, project_reference_id, project_name, category_ids].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = NutanixVolumes.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
