=begin
#Nutanix Volumes APIs

#Configure volumes.

The version of the OpenAPI document: 4.0

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module NutanixVolumes
  class CommonV10StatsDownSamplingOperator
    SUM = "SUM".freeze
    MIN = "MIN".freeze
    MAX = "MAX".freeze
    AVG = "AVG".freeze
    COUNT = "COUNT".freeze
    LAST = "LAST".freeze
    UNKNOWN = "$UNKNOWN".freeze
    REDACTED = "$REDACTED".freeze

    def self.all_vars
      @all_vars ||= [SUM, MIN, MAX, AVG, COUNT, LAST, UNKNOWN, REDACTED].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if CommonV10StatsDownSamplingOperator.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #CommonV10StatsDownSamplingOperator"
    end
  end
end
