=begin
#Nutanix Volumes APIs

#Configure volumes.

The version of the OpenAPI document: 4.0

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module NutanixVolumes
  class CommonV10ConfigEntityType
    CLUSTER = "CLUSTER".freeze
    VM = "VM".freeze
    STORAGE_CONTAINER = "STORAGE_CONTAINER".freeze
    VOLUME_GROUP = "VOLUME_GROUP".freeze
    TASK = "TASK".freeze
    IMAGE = "IMAGE".freeze
    CATEGORY = "CATEGORY".freeze
    NODE = "NODE".freeze
    VPC = "VPC".freeze
    SUBNET = "SUBNET".freeze
    ROUTING_POLICY = "ROUTING_POLICY".freeze
    FLOATING_IP = "FLOATING_IP".freeze
    VPN_GATEWAY = "VPN_GATEWAY".freeze
    VPN_CONNECTION = "VPN_CONNECTION".freeze
    DIRECT_CONNECT = "DIRECT_CONNECT".freeze
    DIRECT_CONNECT_VIF = "DIRECT_CONNECT_VIF".freeze
    VIRTUAL_NIC = "VIRTUAL_NIC".freeze
    VIRTUAL_SWITCH = "VIRTUAL_SWITCH".freeze
    VM_DISK = "VM_DISK".freeze
    VOLUME_DISK = "VOLUME_DISK".freeze
    DISK_RECOVERY_POINT = "DISK_RECOVERY_POINT".freeze
    VTEP_GATEWAY = "VTEP_GATEWAY".freeze
    RECOVERY_PLAN = "RECOVERY_PLAN".freeze
    RECOVERY_PLAN_JOB = "RECOVERY_PLAN_JOB".freeze
    AVAILABILITY_ZONE = "AVAILABILITY_ZONE".freeze
    VIRTUAL_NETWORK = "VIRTUAL_NETWORK".freeze
    CONSISTENCY_GROUP = "CONSISTENCY_GROUP".freeze
    SUBNET_EXTENSION = "SUBNET_EXTENSION".freeze
    UNKNOWN = "$UNKNOWN".freeze
    REDACTED = "$REDACTED".freeze

    def self.all_vars
      @all_vars ||= [CLUSTER, VM, STORAGE_CONTAINER, VOLUME_GROUP, TASK, IMAGE, CATEGORY, NODE, VPC, SUBNET, ROUTING_POLICY, FLOATING_IP, VPN_GATEWAY, VPN_CONNECTION, DIRECT_CONNECT, DIRECT_CONNECT_VIF, VIRTUAL_NIC, VIRTUAL_SWITCH, VM_DISK, VOLUME_DISK, DISK_RECOVERY_POINT, VTEP_GATEWAY, RECOVERY_PLAN, RECOVERY_PLAN_JOB, AVAILABILITY_ZONE, VIRTUAL_NETWORK, CONSISTENCY_GROUP, SUBNET_EXTENSION, UNKNOWN, REDACTED].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if CommonV10ConfigEntityType.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #CommonV10ConfigEntityType"
    end
  end
end
