=begin
#Nutanix Volumes APIs

#Configure volumes.

The version of the OpenAPI document: 4.0

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module NutanixVolumes
  # A model that stores the Volume disk stats.
  class VolumesV40StatsVolumeDiskStats < ApiModelBase
    # A globally unique identifier that represents the tenant that owns this entity. The system automatically assigns it, and it and is immutable from an API consumer perspective (some use cases may cause this Id to change - For instance, a use case may require the transfer of ownership of the entity, but these cases are handled automatically on the server). 
    attr_accessor :tenant_id

    # A globally unique identifier of an instance that is suitable for external consumption. 
    attr_accessor :ext_id

    # A HATEOAS style link for the response.  Each link contains a user-friendly name identifying the link and an address for retrieving the particular resource. 
    attr_accessor :links

    # Uuid of the Volume Disk.
    attr_accessor :volume_disk_ext_id

    # Controller user bytes.
    attr_accessor :controller_user_bytes

    # Controller I/O rate measured in iops.
    attr_accessor :controller_num_iops

    # Controller read I/O measured in iops.
    attr_accessor :controller_num_read_iops

    # Controller write I/O measured in iops.
    attr_accessor :controller_num_write_iops

    # Controller I/O bandwidth measured in Kbps.
    attr_accessor :controller_io_bandwidth_k_bps

    # Controller read I/O bandwidth measured in Kbps.
    attr_accessor :controller_read_io_bandwidth_k_bps

    # Controller write I/O bandwidth measured in Kbps.
    attr_accessor :controller_write_io_bandwidth_k_bps

    # Controller average I/O latency measured in microseconds.
    attr_accessor :controller_avg_io_latency_usecs

    # Controller average read I/O latency measured in microseconds.
    attr_accessor :controller_avg_read_io_latency_usecs

    # Controller average write I/O latency measured in microseconds.
    attr_accessor :controller_avg_write_io_latency_usecs

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'tenant_id' => :'tenantId',
        :'ext_id' => :'extId',
        :'links' => :'links',
        :'volume_disk_ext_id' => :'volumeDiskExtId',
        :'controller_user_bytes' => :'controllerUserBytes',
        :'controller_num_iops' => :'controllerNumIOPS',
        :'controller_num_read_iops' => :'controllerNumReadIOPS',
        :'controller_num_write_iops' => :'controllerNumWriteIOPS',
        :'controller_io_bandwidth_k_bps' => :'controllerIOBandwidthKBps',
        :'controller_read_io_bandwidth_k_bps' => :'controllerReadIOBandwidthKBps',
        :'controller_write_io_bandwidth_k_bps' => :'controllerWriteIOBandwidthKBps',
        :'controller_avg_io_latency_usecs' => :'controllerAvgIOLatencyUsecs',
        :'controller_avg_read_io_latency_usecs' => :'controllerAvgReadIOLatencyUsecs',
        :'controller_avg_write_io_latency_usecs' => :'controllerAvgWriteIOLatencyUsecs'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'tenant_id' => :'String',
        :'ext_id' => :'String',
        :'links' => :'Array<CommonV10ResponseApiLink>',
        :'volume_disk_ext_id' => :'String',
        :'controller_user_bytes' => :'Array<VolumesV40StatsTimeValuePair>',
        :'controller_num_iops' => :'Array<VolumesV40StatsTimeValuePair>',
        :'controller_num_read_iops' => :'Array<VolumesV40StatsTimeValuePair>',
        :'controller_num_write_iops' => :'Array<VolumesV40StatsTimeValuePair>',
        :'controller_io_bandwidth_k_bps' => :'Array<VolumesV40StatsTimeValuePair>',
        :'controller_read_io_bandwidth_k_bps' => :'Array<VolumesV40StatsTimeValuePair>',
        :'controller_write_io_bandwidth_k_bps' => :'Array<VolumesV40StatsTimeValuePair>',
        :'controller_avg_io_latency_usecs' => :'Array<VolumesV40StatsTimeValuePair>',
        :'controller_avg_read_io_latency_usecs' => :'Array<VolumesV40StatsTimeValuePair>',
        :'controller_avg_write_io_latency_usecs' => :'Array<VolumesV40StatsTimeValuePair>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'ext_id',
      ])
    end

    # List of class defined in allOf (OpenAPI v3)
    def self.openapi_all_of
      [
      :'CommonV10ResponseExternalizableAbstractModel'
      ]
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `NutanixVolumes::VolumesV40StatsVolumeDiskStats` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `NutanixVolumes::VolumesV40StatsVolumeDiskStats`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'tenant_id')
        self.tenant_id = attributes[:'tenant_id']
      end

      if attributes.key?(:'ext_id')
        self.ext_id = attributes[:'ext_id']
      end

      if attributes.key?(:'links')
        if (value = attributes[:'links']).is_a?(Array)
          self.links = value
        end
      end

      if attributes.key?(:'volume_disk_ext_id')
        self.volume_disk_ext_id = attributes[:'volume_disk_ext_id']
      end

      if attributes.key?(:'controller_user_bytes')
        if (value = attributes[:'controller_user_bytes']).is_a?(Array)
          self.controller_user_bytes = value
        end
      end

      if attributes.key?(:'controller_num_iops')
        if (value = attributes[:'controller_num_iops']).is_a?(Array)
          self.controller_num_iops = value
        end
      end

      if attributes.key?(:'controller_num_read_iops')
        if (value = attributes[:'controller_num_read_iops']).is_a?(Array)
          self.controller_num_read_iops = value
        end
      end

      if attributes.key?(:'controller_num_write_iops')
        if (value = attributes[:'controller_num_write_iops']).is_a?(Array)
          self.controller_num_write_iops = value
        end
      end

      if attributes.key?(:'controller_io_bandwidth_k_bps')
        if (value = attributes[:'controller_io_bandwidth_k_bps']).is_a?(Array)
          self.controller_io_bandwidth_k_bps = value
        end
      end

      if attributes.key?(:'controller_read_io_bandwidth_k_bps')
        if (value = attributes[:'controller_read_io_bandwidth_k_bps']).is_a?(Array)
          self.controller_read_io_bandwidth_k_bps = value
        end
      end

      if attributes.key?(:'controller_write_io_bandwidth_k_bps')
        if (value = attributes[:'controller_write_io_bandwidth_k_bps']).is_a?(Array)
          self.controller_write_io_bandwidth_k_bps = value
        end
      end

      if attributes.key?(:'controller_avg_io_latency_usecs')
        if (value = attributes[:'controller_avg_io_latency_usecs']).is_a?(Array)
          self.controller_avg_io_latency_usecs = value
        end
      end

      if attributes.key?(:'controller_avg_read_io_latency_usecs')
        if (value = attributes[:'controller_avg_read_io_latency_usecs']).is_a?(Array)
          self.controller_avg_read_io_latency_usecs = value
        end
      end

      if attributes.key?(:'controller_avg_write_io_latency_usecs')
        if (value = attributes[:'controller_avg_write_io_latency_usecs']).is_a?(Array)
          self.controller_avg_write_io_latency_usecs = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      pattern = Regexp.new(/^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$/)
      if !@tenant_id.nil? && @tenant_id !~ pattern
        invalid_properties.push("invalid value for \"tenant_id\", must conform to the pattern #{pattern}.")
      end

      pattern = Regexp.new(/^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$/)
      if !@ext_id.nil? && @ext_id !~ pattern
        invalid_properties.push("invalid value for \"ext_id\", must conform to the pattern #{pattern}.")
      end

      if !@links.nil? && @links.length > 20
        invalid_properties.push('invalid value for "links", number of items must be less than or equal to 20.')
      end

      if !@links.nil? && @links.length < 0
        invalid_properties.push('invalid value for "links", number of items must be greater than or equal to 0.')
      end

      pattern = Regexp.new(/^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$/)
      if !@volume_disk_ext_id.nil? && @volume_disk_ext_id !~ pattern
        invalid_properties.push("invalid value for \"volume_disk_ext_id\", must conform to the pattern #{pattern}.")
      end

      if !@controller_user_bytes.nil? && @controller_user_bytes.length > 100
        invalid_properties.push('invalid value for "controller_user_bytes", number of items must be less than or equal to 100.')
      end

      if !@controller_user_bytes.nil? && @controller_user_bytes.length < 0
        invalid_properties.push('invalid value for "controller_user_bytes", number of items must be greater than or equal to 0.')
      end

      if !@controller_num_iops.nil? && @controller_num_iops.length > 100
        invalid_properties.push('invalid value for "controller_num_iops", number of items must be less than or equal to 100.')
      end

      if !@controller_num_iops.nil? && @controller_num_iops.length < 0
        invalid_properties.push('invalid value for "controller_num_iops", number of items must be greater than or equal to 0.')
      end

      if !@controller_num_read_iops.nil? && @controller_num_read_iops.length > 100
        invalid_properties.push('invalid value for "controller_num_read_iops", number of items must be less than or equal to 100.')
      end

      if !@controller_num_read_iops.nil? && @controller_num_read_iops.length < 0
        invalid_properties.push('invalid value for "controller_num_read_iops", number of items must be greater than or equal to 0.')
      end

      if !@controller_num_write_iops.nil? && @controller_num_write_iops.length > 100
        invalid_properties.push('invalid value for "controller_num_write_iops", number of items must be less than or equal to 100.')
      end

      if !@controller_num_write_iops.nil? && @controller_num_write_iops.length < 0
        invalid_properties.push('invalid value for "controller_num_write_iops", number of items must be greater than or equal to 0.')
      end

      if !@controller_io_bandwidth_k_bps.nil? && @controller_io_bandwidth_k_bps.length > 100
        invalid_properties.push('invalid value for "controller_io_bandwidth_k_bps", number of items must be less than or equal to 100.')
      end

      if !@controller_io_bandwidth_k_bps.nil? && @controller_io_bandwidth_k_bps.length < 0
        invalid_properties.push('invalid value for "controller_io_bandwidth_k_bps", number of items must be greater than or equal to 0.')
      end

      if !@controller_read_io_bandwidth_k_bps.nil? && @controller_read_io_bandwidth_k_bps.length > 100
        invalid_properties.push('invalid value for "controller_read_io_bandwidth_k_bps", number of items must be less than or equal to 100.')
      end

      if !@controller_read_io_bandwidth_k_bps.nil? && @controller_read_io_bandwidth_k_bps.length < 0
        invalid_properties.push('invalid value for "controller_read_io_bandwidth_k_bps", number of items must be greater than or equal to 0.')
      end

      if !@controller_write_io_bandwidth_k_bps.nil? && @controller_write_io_bandwidth_k_bps.length > 100
        invalid_properties.push('invalid value for "controller_write_io_bandwidth_k_bps", number of items must be less than or equal to 100.')
      end

      if !@controller_write_io_bandwidth_k_bps.nil? && @controller_write_io_bandwidth_k_bps.length < 0
        invalid_properties.push('invalid value for "controller_write_io_bandwidth_k_bps", number of items must be greater than or equal to 0.')
      end

      if !@controller_avg_io_latency_usecs.nil? && @controller_avg_io_latency_usecs.length > 100
        invalid_properties.push('invalid value for "controller_avg_io_latency_usecs", number of items must be less than or equal to 100.')
      end

      if !@controller_avg_io_latency_usecs.nil? && @controller_avg_io_latency_usecs.length < 0
        invalid_properties.push('invalid value for "controller_avg_io_latency_usecs", number of items must be greater than or equal to 0.')
      end

      if !@controller_avg_read_io_latency_usecs.nil? && @controller_avg_read_io_latency_usecs.length > 100
        invalid_properties.push('invalid value for "controller_avg_read_io_latency_usecs", number of items must be less than or equal to 100.')
      end

      if !@controller_avg_read_io_latency_usecs.nil? && @controller_avg_read_io_latency_usecs.length < 0
        invalid_properties.push('invalid value for "controller_avg_read_io_latency_usecs", number of items must be greater than or equal to 0.')
      end

      if !@controller_avg_write_io_latency_usecs.nil? && @controller_avg_write_io_latency_usecs.length > 100
        invalid_properties.push('invalid value for "controller_avg_write_io_latency_usecs", number of items must be less than or equal to 100.')
      end

      if !@controller_avg_write_io_latency_usecs.nil? && @controller_avg_write_io_latency_usecs.length < 0
        invalid_properties.push('invalid value for "controller_avg_write_io_latency_usecs", number of items must be greater than or equal to 0.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if !@tenant_id.nil? && @tenant_id !~ Regexp.new(/^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$/)
      return false if !@ext_id.nil? && @ext_id !~ Regexp.new(/^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$/)
      return false if !@links.nil? && @links.length > 20
      return false if !@links.nil? && @links.length < 0
      return false if !@volume_disk_ext_id.nil? && @volume_disk_ext_id !~ Regexp.new(/^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$/)
      return false if !@controller_user_bytes.nil? && @controller_user_bytes.length > 100
      return false if !@controller_user_bytes.nil? && @controller_user_bytes.length < 0
      return false if !@controller_num_iops.nil? && @controller_num_iops.length > 100
      return false if !@controller_num_iops.nil? && @controller_num_iops.length < 0
      return false if !@controller_num_read_iops.nil? && @controller_num_read_iops.length > 100
      return false if !@controller_num_read_iops.nil? && @controller_num_read_iops.length < 0
      return false if !@controller_num_write_iops.nil? && @controller_num_write_iops.length > 100
      return false if !@controller_num_write_iops.nil? && @controller_num_write_iops.length < 0
      return false if !@controller_io_bandwidth_k_bps.nil? && @controller_io_bandwidth_k_bps.length > 100
      return false if !@controller_io_bandwidth_k_bps.nil? && @controller_io_bandwidth_k_bps.length < 0
      return false if !@controller_read_io_bandwidth_k_bps.nil? && @controller_read_io_bandwidth_k_bps.length > 100
      return false if !@controller_read_io_bandwidth_k_bps.nil? && @controller_read_io_bandwidth_k_bps.length < 0
      return false if !@controller_write_io_bandwidth_k_bps.nil? && @controller_write_io_bandwidth_k_bps.length > 100
      return false if !@controller_write_io_bandwidth_k_bps.nil? && @controller_write_io_bandwidth_k_bps.length < 0
      return false if !@controller_avg_io_latency_usecs.nil? && @controller_avg_io_latency_usecs.length > 100
      return false if !@controller_avg_io_latency_usecs.nil? && @controller_avg_io_latency_usecs.length < 0
      return false if !@controller_avg_read_io_latency_usecs.nil? && @controller_avg_read_io_latency_usecs.length > 100
      return false if !@controller_avg_read_io_latency_usecs.nil? && @controller_avg_read_io_latency_usecs.length < 0
      return false if !@controller_avg_write_io_latency_usecs.nil? && @controller_avg_write_io_latency_usecs.length > 100
      return false if !@controller_avg_write_io_latency_usecs.nil? && @controller_avg_write_io_latency_usecs.length < 0
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] tenant_id Value to be assigned
    def tenant_id=(tenant_id)
      if tenant_id.nil?
        fail ArgumentError, 'tenant_id cannot be nil'
      end

      pattern = Regexp.new(/^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$/)
      if tenant_id !~ pattern
        fail ArgumentError, "invalid value for \"tenant_id\", must conform to the pattern #{pattern}."
      end

      @tenant_id = tenant_id
    end

    # Custom attribute writer method with validation
    # @param [Object] ext_id Value to be assigned
    def ext_id=(ext_id)
      pattern = Regexp.new(/^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$/)
      if !ext_id.nil? && ext_id !~ pattern
        fail ArgumentError, "invalid value for \"ext_id\", must conform to the pattern #{pattern}."
      end

      @ext_id = ext_id
    end

    # Custom attribute writer method with validation
    # @param [Object] links Value to be assigned
    def links=(links)
      if links.nil?
        fail ArgumentError, 'links cannot be nil'
      end

      if links.length > 20
        fail ArgumentError, 'invalid value for "links", number of items must be less than or equal to 20.'
      end

      if links.length < 0
        fail ArgumentError, 'invalid value for "links", number of items must be greater than or equal to 0.'
      end

      @links = links
    end

    # Custom attribute writer method with validation
    # @param [Object] volume_disk_ext_id Value to be assigned
    def volume_disk_ext_id=(volume_disk_ext_id)
      if volume_disk_ext_id.nil?
        fail ArgumentError, 'volume_disk_ext_id cannot be nil'
      end

      pattern = Regexp.new(/^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$/)
      if volume_disk_ext_id !~ pattern
        fail ArgumentError, "invalid value for \"volume_disk_ext_id\", must conform to the pattern #{pattern}."
      end

      @volume_disk_ext_id = volume_disk_ext_id
    end

    # Custom attribute writer method with validation
    # @param [Object] controller_user_bytes Value to be assigned
    def controller_user_bytes=(controller_user_bytes)
      if controller_user_bytes.nil?
        fail ArgumentError, 'controller_user_bytes cannot be nil'
      end

      if controller_user_bytes.length > 100
        fail ArgumentError, 'invalid value for "controller_user_bytes", number of items must be less than or equal to 100.'
      end

      if controller_user_bytes.length < 0
        fail ArgumentError, 'invalid value for "controller_user_bytes", number of items must be greater than or equal to 0.'
      end

      @controller_user_bytes = controller_user_bytes
    end

    # Custom attribute writer method with validation
    # @param [Object] controller_num_iops Value to be assigned
    def controller_num_iops=(controller_num_iops)
      if controller_num_iops.nil?
        fail ArgumentError, 'controller_num_iops cannot be nil'
      end

      if controller_num_iops.length > 100
        fail ArgumentError, 'invalid value for "controller_num_iops", number of items must be less than or equal to 100.'
      end

      if controller_num_iops.length < 0
        fail ArgumentError, 'invalid value for "controller_num_iops", number of items must be greater than or equal to 0.'
      end

      @controller_num_iops = controller_num_iops
    end

    # Custom attribute writer method with validation
    # @param [Object] controller_num_read_iops Value to be assigned
    def controller_num_read_iops=(controller_num_read_iops)
      if controller_num_read_iops.nil?
        fail ArgumentError, 'controller_num_read_iops cannot be nil'
      end

      if controller_num_read_iops.length > 100
        fail ArgumentError, 'invalid value for "controller_num_read_iops", number of items must be less than or equal to 100.'
      end

      if controller_num_read_iops.length < 0
        fail ArgumentError, 'invalid value for "controller_num_read_iops", number of items must be greater than or equal to 0.'
      end

      @controller_num_read_iops = controller_num_read_iops
    end

    # Custom attribute writer method with validation
    # @param [Object] controller_num_write_iops Value to be assigned
    def controller_num_write_iops=(controller_num_write_iops)
      if controller_num_write_iops.nil?
        fail ArgumentError, 'controller_num_write_iops cannot be nil'
      end

      if controller_num_write_iops.length > 100
        fail ArgumentError, 'invalid value for "controller_num_write_iops", number of items must be less than or equal to 100.'
      end

      if controller_num_write_iops.length < 0
        fail ArgumentError, 'invalid value for "controller_num_write_iops", number of items must be greater than or equal to 0.'
      end

      @controller_num_write_iops = controller_num_write_iops
    end

    # Custom attribute writer method with validation
    # @param [Object] controller_io_bandwidth_k_bps Value to be assigned
    def controller_io_bandwidth_k_bps=(controller_io_bandwidth_k_bps)
      if controller_io_bandwidth_k_bps.nil?
        fail ArgumentError, 'controller_io_bandwidth_k_bps cannot be nil'
      end

      if controller_io_bandwidth_k_bps.length > 100
        fail ArgumentError, 'invalid value for "controller_io_bandwidth_k_bps", number of items must be less than or equal to 100.'
      end

      if controller_io_bandwidth_k_bps.length < 0
        fail ArgumentError, 'invalid value for "controller_io_bandwidth_k_bps", number of items must be greater than or equal to 0.'
      end

      @controller_io_bandwidth_k_bps = controller_io_bandwidth_k_bps
    end

    # Custom attribute writer method with validation
    # @param [Object] controller_read_io_bandwidth_k_bps Value to be assigned
    def controller_read_io_bandwidth_k_bps=(controller_read_io_bandwidth_k_bps)
      if controller_read_io_bandwidth_k_bps.nil?
        fail ArgumentError, 'controller_read_io_bandwidth_k_bps cannot be nil'
      end

      if controller_read_io_bandwidth_k_bps.length > 100
        fail ArgumentError, 'invalid value for "controller_read_io_bandwidth_k_bps", number of items must be less than or equal to 100.'
      end

      if controller_read_io_bandwidth_k_bps.length < 0
        fail ArgumentError, 'invalid value for "controller_read_io_bandwidth_k_bps", number of items must be greater than or equal to 0.'
      end

      @controller_read_io_bandwidth_k_bps = controller_read_io_bandwidth_k_bps
    end

    # Custom attribute writer method with validation
    # @param [Object] controller_write_io_bandwidth_k_bps Value to be assigned
    def controller_write_io_bandwidth_k_bps=(controller_write_io_bandwidth_k_bps)
      if controller_write_io_bandwidth_k_bps.nil?
        fail ArgumentError, 'controller_write_io_bandwidth_k_bps cannot be nil'
      end

      if controller_write_io_bandwidth_k_bps.length > 100
        fail ArgumentError, 'invalid value for "controller_write_io_bandwidth_k_bps", number of items must be less than or equal to 100.'
      end

      if controller_write_io_bandwidth_k_bps.length < 0
        fail ArgumentError, 'invalid value for "controller_write_io_bandwidth_k_bps", number of items must be greater than or equal to 0.'
      end

      @controller_write_io_bandwidth_k_bps = controller_write_io_bandwidth_k_bps
    end

    # Custom attribute writer method with validation
    # @param [Object] controller_avg_io_latency_usecs Value to be assigned
    def controller_avg_io_latency_usecs=(controller_avg_io_latency_usecs)
      if controller_avg_io_latency_usecs.nil?
        fail ArgumentError, 'controller_avg_io_latency_usecs cannot be nil'
      end

      if controller_avg_io_latency_usecs.length > 100
        fail ArgumentError, 'invalid value for "controller_avg_io_latency_usecs", number of items must be less than or equal to 100.'
      end

      if controller_avg_io_latency_usecs.length < 0
        fail ArgumentError, 'invalid value for "controller_avg_io_latency_usecs", number of items must be greater than or equal to 0.'
      end

      @controller_avg_io_latency_usecs = controller_avg_io_latency_usecs
    end

    # Custom attribute writer method with validation
    # @param [Object] controller_avg_read_io_latency_usecs Value to be assigned
    def controller_avg_read_io_latency_usecs=(controller_avg_read_io_latency_usecs)
      if controller_avg_read_io_latency_usecs.nil?
        fail ArgumentError, 'controller_avg_read_io_latency_usecs cannot be nil'
      end

      if controller_avg_read_io_latency_usecs.length > 100
        fail ArgumentError, 'invalid value for "controller_avg_read_io_latency_usecs", number of items must be less than or equal to 100.'
      end

      if controller_avg_read_io_latency_usecs.length < 0
        fail ArgumentError, 'invalid value for "controller_avg_read_io_latency_usecs", number of items must be greater than or equal to 0.'
      end

      @controller_avg_read_io_latency_usecs = controller_avg_read_io_latency_usecs
    end

    # Custom attribute writer method with validation
    # @param [Object] controller_avg_write_io_latency_usecs Value to be assigned
    def controller_avg_write_io_latency_usecs=(controller_avg_write_io_latency_usecs)
      if controller_avg_write_io_latency_usecs.nil?
        fail ArgumentError, 'controller_avg_write_io_latency_usecs cannot be nil'
      end

      if controller_avg_write_io_latency_usecs.length > 100
        fail ArgumentError, 'invalid value for "controller_avg_write_io_latency_usecs", number of items must be less than or equal to 100.'
      end

      if controller_avg_write_io_latency_usecs.length < 0
        fail ArgumentError, 'invalid value for "controller_avg_write_io_latency_usecs", number of items must be greater than or equal to 0.'
      end

      @controller_avg_write_io_latency_usecs = controller_avg_write_io_latency_usecs
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          tenant_id == o.tenant_id &&
          ext_id == o.ext_id &&
          links == o.links &&
          volume_disk_ext_id == o.volume_disk_ext_id &&
          controller_user_bytes == o.controller_user_bytes &&
          controller_num_iops == o.controller_num_iops &&
          controller_num_read_iops == o.controller_num_read_iops &&
          controller_num_write_iops == o.controller_num_write_iops &&
          controller_io_bandwidth_k_bps == o.controller_io_bandwidth_k_bps &&
          controller_read_io_bandwidth_k_bps == o.controller_read_io_bandwidth_k_bps &&
          controller_write_io_bandwidth_k_bps == o.controller_write_io_bandwidth_k_bps &&
          controller_avg_io_latency_usecs == o.controller_avg_io_latency_usecs &&
          controller_avg_read_io_latency_usecs == o.controller_avg_read_io_latency_usecs &&
          controller_avg_write_io_latency_usecs == o.controller_avg_write_io_latency_usecs
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [tenant_id, ext_id, links, volume_disk_ext_id, controller_user_bytes, controller_num_iops, controller_num_read_iops, controller_num_write_iops, controller_io_bandwidth_k_bps, controller_read_io_bandwidth_k_bps, controller_write_io_bandwidth_k_bps, controller_avg_io_latency_usecs, controller_avg_read_io_latency_usecs, controller_avg_write_io_latency_usecs].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
