=begin
#Nutanix Volumes APIs

#Configure volumes.

The version of the OpenAPI document: 4.0

Generated by: https://openapi-generator.tech
Generator version: 7.16.0

=end

require 'date'
require 'time'

module NutanixVolumes
  class VolumesV40ConfigAttachmentType
    NONE = "NONE".freeze
    DIRECT = "DIRECT".freeze
    EXTERNAL = "EXTERNAL".freeze
    _UNKNOWN = "$UNKNOWN".freeze
    _REDACTED = "$REDACTED".freeze

    def self.all_vars
      @all_vars ||= [NONE, DIRECT, EXTERNAL, _UNKNOWN, _REDACTED].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if VolumesV40ConfigAttachmentType.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #VolumesV40ConfigAttachmentType"
    end
  end
end
