=begin
#Nutanix Volumes APIs

#Configure volumes.

The version of the OpenAPI document: 4.0

Generated by: https://openapi-generator.tech
Generator version: 7.16.0

=end

require 'date'
require 'time'

module NutanixVolumes
  # A model that represents an iSCSI client that can be associated with a Volume Group as an external attachment.
  class VolumesV40ConfigIscsiClient
    # A globally unique identifier that represents the tenant that owns this entity. The system automatically assigns it, and it and is immutable from an API consumer perspective (some use cases may cause this Id to change - For instance, a use case may require the transfer of ownership of the entity, but these cases are handled automatically on the server). 
    attr_accessor :tenant_id

    # A globally unique identifier of an instance that is suitable for external consumption. 
    attr_accessor :ext_id

    # A HATEOAS style link for the response.  Each link contains a user-friendly name identifying the link and an address for retrieving the particular resource. 
    attr_accessor :links

    # iSCSI initiator name. Exactly one of iscsiInitiatorName and iscsiInitiatorNetworkId must be specified during the attach operation. This field is immutable.
    attr_accessor :iscsi_initiator_name

    attr_accessor :iscsi_initiator_network_id

    # iSCSI initiator client secret in case of CHAP authentication. This field should not be provided if the authentication type is not set to CHAP.
    attr_accessor :client_secret

    attr_accessor :enabled_authentications

    attr_accessor :attached_targets

    # Number of virtual targets generated for the iSCSI target. This field is immutable.
    attr_accessor :num_virtual_targets

    # The UUID of the cluster that will host the iSCSI client. This field is read-only.
    attr_accessor :cluster_reference

    attr_accessor :attachment_site

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'tenant_id' => :'tenantId',
        :'ext_id' => :'extId',
        :'links' => :'links',
        :'iscsi_initiator_name' => :'iscsiInitiatorName',
        :'iscsi_initiator_network_id' => :'iscsiInitiatorNetworkId',
        :'client_secret' => :'clientSecret',
        :'enabled_authentications' => :'enabledAuthentications',
        :'attached_targets' => :'attachedTargets',
        :'num_virtual_targets' => :'numVirtualTargets',
        :'cluster_reference' => :'clusterReference',
        :'attachment_site' => :'attachmentSite'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'tenant_id' => :'String',
        :'ext_id' => :'String',
        :'links' => :'Array<CommonV10ResponseApiLink>',
        :'iscsi_initiator_name' => :'String',
        :'iscsi_initiator_network_id' => :'CommonV10ConfigIPAddressOrFQDN',
        :'client_secret' => :'String',
        :'enabled_authentications' => :'VolumesV40ConfigAuthenticationType',
        :'attached_targets' => :'Array<VolumesV40ConfigTargetParam>',
        :'num_virtual_targets' => :'Integer',
        :'cluster_reference' => :'String',
        :'attachment_site' => :'VolumesV40ConfigVolumeGroupAttachmentSite'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'ext_id',
      ])
    end

    # List of class defined in allOf (OpenAPI v3)
    def self.openapi_all_of
      [
      :'CommonV10ResponseExternalizableAbstractModel'
      ]
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `NutanixVolumes::VolumesV40ConfigIscsiClient` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `NutanixVolumes::VolumesV40ConfigIscsiClient`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'tenant_id')
        self.tenant_id = attributes[:'tenant_id']
      end

      if attributes.key?(:'ext_id')
        self.ext_id = attributes[:'ext_id']
      end

      if attributes.key?(:'links')
        if (value = attributes[:'links']).is_a?(Array)
          self.links = value
        end
      end

      if attributes.key?(:'iscsi_initiator_name')
        self.iscsi_initiator_name = attributes[:'iscsi_initiator_name']
      end

      if attributes.key?(:'iscsi_initiator_network_id')
        self.iscsi_initiator_network_id = attributes[:'iscsi_initiator_network_id']
      end

      if attributes.key?(:'client_secret')
        self.client_secret = attributes[:'client_secret']
      end

      if attributes.key?(:'enabled_authentications')
        self.enabled_authentications = attributes[:'enabled_authentications']
      end

      if attributes.key?(:'attached_targets')
        if (value = attributes[:'attached_targets']).is_a?(Array)
          self.attached_targets = value
        end
      end

      if attributes.key?(:'num_virtual_targets')
        self.num_virtual_targets = attributes[:'num_virtual_targets']
      end

      if attributes.key?(:'cluster_reference')
        self.cluster_reference = attributes[:'cluster_reference']
      end

      if attributes.key?(:'attachment_site')
        self.attachment_site = attributes[:'attachment_site']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      pattern = Regexp.new(/^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$/)
      if !@tenant_id.nil? && @tenant_id !~ pattern
        invalid_properties.push("invalid value for \"tenant_id\", must conform to the pattern #{pattern}.")
      end

      pattern = Regexp.new(/^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$/)
      if !@ext_id.nil? && @ext_id !~ pattern
        invalid_properties.push("invalid value for \"ext_id\", must conform to the pattern #{pattern}.")
      end

      if !@links.nil? && @links.length > 20
        invalid_properties.push('invalid value for "links", number of items must be less than or equal to 20.')
      end

      if !@links.nil? && @links.length < 0
        invalid_properties.push('invalid value for "links", number of items must be greater than or equal to 0.')
      end

      if !@iscsi_initiator_name.nil? && @iscsi_initiator_name.to_s.length > 64
        invalid_properties.push('invalid value for "iscsi_initiator_name", the character length must be smaller than or equal to 64.')
      end

      if !@client_secret.nil? && @client_secret.to_s.length > 16
        invalid_properties.push('invalid value for "client_secret", the character length must be smaller than or equal to 16.')
      end

      if !@client_secret.nil? && @client_secret.to_s.length < 12
        invalid_properties.push('invalid value for "client_secret", the character length must be greater than or equal to 12.')
      end

      if !@attached_targets.nil? && @attached_targets.length > 128
        invalid_properties.push('invalid value for "attached_targets", number of items must be less than or equal to 128.')
      end

      if !@attached_targets.nil? && @attached_targets.length < 0
        invalid_properties.push('invalid value for "attached_targets", number of items must be greater than or equal to 0.')
      end

      pattern = Regexp.new(/^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$/)
      if !@cluster_reference.nil? && @cluster_reference !~ pattern
        invalid_properties.push("invalid value for \"cluster_reference\", must conform to the pattern #{pattern}.")
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if !@tenant_id.nil? && @tenant_id !~ Regexp.new(/^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$/)
      return false if !@ext_id.nil? && @ext_id !~ Regexp.new(/^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$/)
      return false if !@links.nil? && @links.length > 20
      return false if !@links.nil? && @links.length < 0
      return false if !@iscsi_initiator_name.nil? && @iscsi_initiator_name.to_s.length > 64
      return false if !@client_secret.nil? && @client_secret.to_s.length > 16
      return false if !@client_secret.nil? && @client_secret.to_s.length < 12
      return false if !@attached_targets.nil? && @attached_targets.length > 128
      return false if !@attached_targets.nil? && @attached_targets.length < 0
      return false if !@cluster_reference.nil? && @cluster_reference !~ Regexp.new(/^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$/)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] tenant_id Value to be assigned
    def tenant_id=(tenant_id)
      if tenant_id.nil?
        fail ArgumentError, 'tenant_id cannot be nil'
      end

      pattern = Regexp.new(/^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$/)
      if tenant_id !~ pattern
        fail ArgumentError, "invalid value for \"tenant_id\", must conform to the pattern #{pattern}."
      end

      @tenant_id = tenant_id
    end

    # Custom attribute writer method with validation
    # @param [Object] ext_id Value to be assigned
    def ext_id=(ext_id)
      pattern = Regexp.new(/^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$/)
      if !ext_id.nil? && ext_id !~ pattern
        fail ArgumentError, "invalid value for \"ext_id\", must conform to the pattern #{pattern}."
      end

      @ext_id = ext_id
    end

    # Custom attribute writer method with validation
    # @param [Object] links Value to be assigned
    def links=(links)
      if links.nil?
        fail ArgumentError, 'links cannot be nil'
      end

      if links.length > 20
        fail ArgumentError, 'invalid value for "links", number of items must be less than or equal to 20.'
      end

      if links.length < 0
        fail ArgumentError, 'invalid value for "links", number of items must be greater than or equal to 0.'
      end

      @links = links
    end

    # Custom attribute writer method with validation
    # @param [Object] iscsi_initiator_name Value to be assigned
    def iscsi_initiator_name=(iscsi_initiator_name)
      if iscsi_initiator_name.nil?
        fail ArgumentError, 'iscsi_initiator_name cannot be nil'
      end

      if iscsi_initiator_name.to_s.length > 64
        fail ArgumentError, 'invalid value for "iscsi_initiator_name", the character length must be smaller than or equal to 64.'
      end

      @iscsi_initiator_name = iscsi_initiator_name
    end

    # Custom attribute writer method with validation
    # @param [Object] client_secret Value to be assigned
    def client_secret=(client_secret)
      if client_secret.nil?
        fail ArgumentError, 'client_secret cannot be nil'
      end

      if client_secret.to_s.length > 16
        fail ArgumentError, 'invalid value for "client_secret", the character length must be smaller than or equal to 16.'
      end

      if client_secret.to_s.length < 12
        fail ArgumentError, 'invalid value for "client_secret", the character length must be greater than or equal to 12.'
      end

      @client_secret = client_secret
    end

    # Custom attribute writer method with validation
    # @param [Object] attached_targets Value to be assigned
    def attached_targets=(attached_targets)
      if attached_targets.nil?
        fail ArgumentError, 'attached_targets cannot be nil'
      end

      if attached_targets.length > 128
        fail ArgumentError, 'invalid value for "attached_targets", number of items must be less than or equal to 128.'
      end

      if attached_targets.length < 0
        fail ArgumentError, 'invalid value for "attached_targets", number of items must be greater than or equal to 0.'
      end

      @attached_targets = attached_targets
    end

    # Custom attribute writer method with validation
    # @param [Object] cluster_reference Value to be assigned
    def cluster_reference=(cluster_reference)
      if cluster_reference.nil?
        fail ArgumentError, 'cluster_reference cannot be nil'
      end

      pattern = Regexp.new(/^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$/)
      if cluster_reference !~ pattern
        fail ArgumentError, "invalid value for \"cluster_reference\", must conform to the pattern #{pattern}."
      end

      @cluster_reference = cluster_reference
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          tenant_id == o.tenant_id &&
          ext_id == o.ext_id &&
          links == o.links &&
          iscsi_initiator_name == o.iscsi_initiator_name &&
          iscsi_initiator_network_id == o.iscsi_initiator_network_id &&
          client_secret == o.client_secret &&
          enabled_authentications == o.enabled_authentications &&
          attached_targets == o.attached_targets &&
          num_virtual_targets == o.num_virtual_targets &&
          cluster_reference == o.cluster_reference &&
          attachment_site == o.attachment_site
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [tenant_id, ext_id, links, iscsi_initiator_name, iscsi_initiator_network_id, client_secret, enabled_authentications, attached_targets, num_virtual_targets, cluster_reference, attachment_site].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = NutanixVolumes.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
